config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  
  unauthenticated do
    root 'welcome#home', as: :unauthenticated_root
  end

  root to: 'home#index'
  
  get '/groups/all' => "groups#index"
  
  resources :groups, only: %i[index create new update all] do
    resources :purchases, only: %i[index create new show]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :purchase_groups, dependent: :destroy
  has_many :purchases, through: :purchase_groups

  validates :name, presence: true, uniqueness: true

  def ordered_purchases
    purchases.order(created_at: :desc)
  end

  def total_purchases
    total = 0
    purchases.each do |purchase|
      total += purchase.amount
    end
    total
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    groups = Group.includes(:purchases).where(user: current_user).order(created_at: :desc)
    limit = 3
    limit = nil if request.env['PATH_INFO'].include? 'all'
    @groups = groups.limit(limit)
    @total = 0
    groups.each do |group|
      @total += group.total_purchases
    end
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def home; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon).merge(user: current_user)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-fields">
    <%= form.text_field :name, placeholder: 'Name of category', class: "links links_with_border"  %>
    <%= form.text_field :icon, placeholder: 'Icon URL', class: "links links_with_border"  %>
  </div>

  <div>
    <%= form.submit "Add category", id: 'add-category-btn' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="category">
  <% if group.icon.present? %>
    <%= image_tag group.icon, class: "category-icon" %>
  <% else %>
    <%= image_tag "default-category-icon.png", class: "category-icon" %>
  <% end %>
  <div class="category-info">
    <h3><%= group.name %></h3>
    <p>Purchases: <strong>$<%= group.total_purchases %></strong></p>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<header class="categories-nav">
  <h2>Categories</h2>
</header>
<div class="groups-cost-wrapper">
  <span>Overall purchases: <strong>$<%= @total %></strong></span>
</div>
<% if @groups.empty? %>
  <p class="no-content-msg">There are no categories added currently</p>
<% else %>
  <div class="categories-wrapper">
    <div id="categories">
      <% @groups.each do |group| %>
        <a href= <%= group_purchases_path(group) %> class="category-card"><%= render group %></a>
      <% end %>
    </div>
  </div>
  <% if request.env['PATH_INFO'].include? 'all' %>
    <a href= <%= groups_path %>  id="all-categories-link">Show less</a>
  <% else %>
    <a href= <%= groups_all_path %>  id="all-categories-link">Show all</a>
  <%end%>
<% end %>
<%= link_to "New category", new_group_path, id: "new-category-btn" %>

app/views/groups/new.html.erb
<div class="cat-wrapper">
  <h1>New category</h1>
</div>

<div class="cat-form">
  <%= render "form", group: @group %>

  <br>

  <div>
    <%= link_to "Back to groups", groups_path %>
  </div>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>