config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  
  unauthenticated do
    root 'welcome#home', as: :unauthenticated_root
  end

  root to: 'home#index'
  
  get '/groups/all' => "groups#index"
  
  resources :groups, only: %i[index create new update all] do
    resources :purchases, only: %i[index create new show]
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]

  # GET /purchases or /purchases.json
  def index
    @group = Group.find_by(id: params[:group_id])
    @purchases = if @group.present?
                   @group.purchases
                 else
                   Purchase.all
                 end
  end

  # GET /purchases/1 or /purchases/1.json
  def show
    @group = Group.find_by(id: params[:group_id]) || @purchase.groups.first
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
    @groups = []
    @group = params[:group_id]
    groups = Group.where(id: params[:group_id])
    groups.each do |group|
      @groups << [group.name, group.id]
    end
  end

  # GET /purchases/1/edit
  def edit; end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.create(name: purchase_params[:name], amount: purchase_params[:amount],
                                reciever: purchase_params[:reciever], description: purchase_params[:description],
                                author: current_user)
    purchase_group = PurchaseGroup.create(group_id: purchase_params[:group], purchase_id: @purchase.id)

    respond_to do |format|
      if purchase_group.save
        format.html { redirect_to group_purchases_url(params[:group_id]), notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        @purchase.destroy
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to group_purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:name, :amount, :group, :reciever, :description)
  end
end

app/views/purchases/_form.html.erb
<%= form_with(model: purchase, url: group_purchases_path(group)) do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-fields">
    <%= form.text_field :name, placeholder: 'Name of the item..', class: "links links_with_border", :required => true %>
    
    <%= form.text_field :reciever, placeholder: 'To:', class: "links links_with_border", :required => true %>
    <%= form.number_field :amount, placeholder: 'Amount in USD', class: "links links_with_border", min: 0, :required => true %>
    
    <%= form.text_area :description, placeholder: 'Description..', class: "links links_with_border", :required => true %>
  </div>

  <div>
    <%= form.select :group, @groups, { :include_blank => '-- Select category --' }, :required => true %>
  </div>

  <div>
    <%= form.submit "Add purchase", id: 'add-puchase-btn' %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div class="single-purchase" >

  <p id="purchase-top-section">
    <span><%= purchase.name%></span>
    <span id="price"><strong>$<%= purchase.amount %></strong></span>
  </p>

  <p>
    <span id="created-date"><%= purchase.created_at.to_s.split(' ')[0]%></span>
  </p>
</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<header class="navigation">
  <a href=<%= groups_path %> id="back-btn"><i class="fa-solid fa-arrow-left"></i>Back</a>
  <h2>Purchases</h2>
  <a href="#"></a>
</header>

<div class="add-purchase-wrapper">
  <span>Total purchases: <strong>$<%= @group.total_purchases %></strong></span>
  <%= link_to "New purchase", new_group_purchase_path(@group), id: "new-purchase-btn" %>
</div>
<% if @group.purchases.empty? %>
  <p class="no-content-msg">There are no purchases added currently</p>
<% else %>
  <div class="purchases-wrapper">
    <div id="purchases">
      <% @group.ordered_purchases.each do |purchase| %>
        <a href=<%= group_purchase_path(@group, purchase) %> id="purchase-links"><%= render purchase %></a>
      <% end %>
    </div>
  </div>
<% end %>

app/views/purchases/new.html.erb
<header class="navigation">
    <a href=<%= group_purchases_path(@group) %> id="back-btn"><i class="fa-solid fa-arrow-left"></i>Back</a>
    <h2>Purchases</h2>
    <a href="#"></a>
  </header>  
  <div class="purchase-form">
    <h3>New purchase</h3>

    <%= render "form", purchase: @purchase, groups: @groups, group: @group %>
  </div>

app/views/purchases/show.html.erb
<header class="navigation">
  <a href="<%= group_purchases_path(@group) %>" id="back-btn"> <i class="fa-solid fa-arrow-left"></i> Back</a>
  <h2>Detail</h2>
  <a href="#"></a>
</header>

<div class="detail">
  <h2 class=""><%= @purchase.name%></h2>
  <p class="description dl"><%= @purchase.description%></p>
  <div class="reciever-info dl">
    <p id="reciever">Reciever: <%= @purchase.reciever%></p>
    <p class="created-date"><%= @purchase.created_at%></p>
  </div>
  <p class="price"><span>TOTAL PAYMENT</span><strong>$<%= @purchase.amount %></strong></p>
</div>